package com.sosnowskydevelop.saratovmonuments.utilities

const val LOG_TAG = "sosnovskiim"

const val REQUEST_KEY_CATEGORY_ID_FROM_MONUMENTS_TO_MONUMENT_SEARCH =
    "requestKeyCategoryIdFromMonumentsToMonumentSearch"
const val BUNDLE_KEY_CATEGORY_ID_FROM_MONUMENTS_TO_MONUMENT_SEARCH =
    "bundleKeyCategoryIdFromMonumentsToMonumentSearch"
const val REQUEST_KEY_CATEGORY_ID_FROM_CATEGORIES_TO_MONUMENTS =
    "requestKeyCategoryIdFromCategoriesToMonuments"
const val BUNDLE_KEY_CATEGORY_ID_FROM_CATEGORIES_TO_MONUMENTS =
    "bundleKeyCategoryIdFromCategoriesToMonuments"
const val REQUEST_KEY_CATEGORY_ID_FROM_MONUMENTS_TO_MONUMENT_PRIMARY =
    "requestKeyCategoryIdFromMonumentsToMonumentPrimary"
const val BUNDLE_KEY_CATEGORY_ID_FROM_MONUMENTS_TO_MONUMENT_PRIMARY =
    "bundleKeyCategoryIdFromMonumentsToMonumentPrimary"
const val REQUEST_KEY_MONUMENT_ID_FROM_MONUMENTS_TO_MONUMENT_PRIMARY =
    "requestKeyMonumentIdFromMonumentsToMonumentPrimary"
const val BUNDLE_KEY_MONUMENT_ID_FROM_MONUMENTS_TO_MONUMENT_PRIMARY =
    "bundleKeyMonumentIdFromMonumentsToMonumentPrimary"
const val REQUEST_KEY_MONUMENT_ID_FROM_MONUMENT_PRIMARY_TO_MONUMENT_MAP =
    "requestKeyMonumentIdFromMonumentPrimaryToMonumentMap"
const val BUNDLE_KEY_MONUMENT_ID_FROM_MONUMENT_PRIMARY_TO_MONUMENT_MAP =
    "bundleKeyMonumentIdFromMonumentPrimaryToMonumentMap"